### ISSUE TITLE
It cannot be compiled correctly

### ISSUE THREAD

**Issue by Dreamer-Sea** [orsalmon/ORB_SLAM2_GTSAM#1]
The output of compiling is 'make: *** No targets specified and no makefile found. Stop.' I have installed all the dependencies. The gtsam and orb slam 2 can be compiled correctly. Is there anything else should I do before compile the ORB_SLAM2_GTSAM? If yes, please tell me, thank a lot.

**Comment by orsalmon** [comment]
Hi, Sorry about that.
I have made some updates and now everything is compiling and ok. Please follow step 2 and 3 in the README and make sure you are using the ./build.sh script to compile (or just use cmake commands).
I tested a fresh build on my laptop to verify.
